// Run after `vite build`. The build is ONE html file with inline script and
// style, so a plain 'self' policy would block it and 'unsafe-inline' would
// let any injected script run. Instead every inline block is allowed by its
// SHA-256 hash: only the code we just built can execute.
// Output: a nginx snippet with the security headers (include it in the
// server block that serves dist/).

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const html = readFileSync("dist/index.html", "utf8");

// The browser may only call the API origin this build was made for. Vite
// bakes VITE_API_BASE_URL into the bundle; it is read here the same way
// (shell variable first, then .env.production, then .env).
function apiBaseUrl() {
  if (process.env.VITE_API_BASE_URL) return process.env.VITE_API_BASE_URL;
  for (const file of [".env.production", ".env"]) {
    if (!existsSync(file)) continue;
    const match = readFileSync(file, "utf8").match(/^VITE_API_BASE_URL=(.*)$/m);
    if (match) return match[1].trim().replace(/^["']|["']$/g, "");
  }
  return "";
}

function connectSources() {
  const base = apiBaseUrl();
  if (!base.startsWith("http")) return "'self'"; // same-origin /api
  const url = new URL(base);
  const local = ["localhost", "127.0.0.1"].includes(url.hostname);
  if (url.protocol !== "https:" && !local) {
    throw new Error("VITE_API_BASE_URL must be https for a real build");
  }
  if (!url.pathname.replace(/\/$/, "").endsWith("/api")) {
    console.warn("warning: VITE_API_BASE_URL should end with /api");
  }
  return `'self' ${url.origin}`;
}

function hashes(tag) {
  const out = [];
  const pattern = new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)</${tag}>`, "g");
  for (const match of html.matchAll(pattern)) {
    if (match[1].trim() === "") continue;
    out.push(`'sha256-${createHash("sha256").update(match[1]).digest("base64")}'`);
  }
  return out;
}

const scripts = hashes("script");
const styles = hashes("style");
if (scripts.length === 0) throw new Error("no inline script found: check the build");

const csp = [
  "default-src 'none'",
  `script-src ${scripts.join(" ")}`,
  `style-src https://fonts.googleapis.com ${styles.join(" ")}`,
  // React and the charts set style attributes; those cannot be hashed.
  "style-src-attr 'unsafe-inline'",
  "font-src https://fonts.gstatic.com",
  "img-src 'self' data:",
  // Only the API origin of this build (see connectSources).
  `connect-src ${connectSources()}`,
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
].join("; ");

const headers = [
  ["Content-Security-Policy", csp],
  ["X-Content-Type-Options", "nosniff"],
  ["X-Frame-Options", "DENY"],
  ["Referrer-Policy", "no-referrer"],
  ["Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=(), usb=()"],
  ["Cross-Origin-Opener-Policy", "same-origin"],
  ["Cross-Origin-Resource-Policy", "same-origin"],
  ["Strict-Transport-Security", "max-age=31536000; includeSubDomains"],
];

// nginx form (for a server that serves dist/ itself).
const nginx = headers
  .map(([name, value]) => `add_header ${name} "${value}" always;`)
  .join("\n");
writeFileSync(
  "dist-security-headers.conf",
  `# Generated by frontend/scripts/csp.mjs: do not edit, rebuild instead.\n${nginx}\n`
);

// Cloudflare Pages form: a _headers file inside the build output.
const pages = headers.map(([name, value]) => `  ${name}: ${value}`).join("\n");
writeFileSync("dist/_headers", `/*\n${pages}\n`);

console.log(`CSP written: ${scripts.length} script and ${styles.length} style hashes`);
